CREATE DATABASE IF NOT EXISTS mydemo1 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'mydemo1'@'%' IDENTIFIED BY 'mydemo1pass';
GRANT ALL PRIVILEGES ON mydemo1.* TO 'mydemo1'@'%';

CREATE DATABASE IF NOT EXISTS mydemo2 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'mydemo2'@'%' IDENTIFIED BY 'mydemo2pass';
GRANT ALL PRIVILEGES ON mydemo2.* TO 'mydemo2'@'%';

FLUSH PRIVILEGES;